# Generated by Django 4.2.5 on 2023-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id_associado', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField()),
                ('email', models.EmailField(help_text=200, max_length=254)),
            ],
        ),
    ]
