# Generated by Django 4.2.5 on 2023-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='associado',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
