# Generated by Django 4.2.5 on 2023-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_alter_associado_cpf_alter_associado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
