# Generated by Django 4.2.5 on 2023-10-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_alter_associado_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Associado',
        ),
    ]
