# Generated by Django 4.2.5 on 2023-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
